# Generated by Django 5.0.6 on 2024-06-23 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReactCard',
            new_name='React',
        ),
    ]
