# Generated by Django 5.0.6 on 2024-06-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_reactcard_react'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='react',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
