# Generated by Django 5.0.6 on 2024-07-18 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_react_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='link',
        ),
    ]
